# Generated by Django 5.1.6 on 2025-03-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='needs_cookies',
            field=models.BooleanField(default=False, help_text='Does access to this channels content require cookies?'),
        ),
        migrations.AddField(
            model_name='video',
            name='needs_cookies',
            field=models.BooleanField(default=False, help_text='Does access to this video require cookies?'),
        ),
    ]
