# Generated by Django 5.1.6 on 2025-03-23 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidar', '0002_channel_needs_cookies_video_needs_cookies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highlight',
            options={'ordering': ['video', 'point'], 'permissions': [('change_chapter', 'Can change chapters')]},
        ),
    ]
