# Generated by Django 5.1.6 on 2025-03-30 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidar', '0003_alter_highlight_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='next_playlist',
            field=models.OneToOneField(blank=True, help_text='When auto-playing, you can set the next playlist to automatically go into. i.e. music playlists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_playlist', to='vidar.playlist'),
        ),
    ]
