name: Django tests

on:
  push:
    branches: [ master ]
    tags-ignore:
      - '20*'
  pull_request:
    branches: [ master ]

jobs:
  call-workflow-passing-data:
    uses: django-vidar/django-vidar/.github/workflows/tests.yml@master
