name: Push or PR to master runs django tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  call-django-tests-workflow:
    uses: ./.github/workflows/run-django-tests.yml
    secrets: inherit
