name: Push or PR to master runs django tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  call-workflow-passing-data:
    uses: django-vidar/django-vidar/.github/workflows/run-django-tests.yml@master
    secrets: inherit
  call-demo-builder-workflow:
    needs: call-django-tests-workflow
    uses: django-vidar/django-vidar/.github/workflows/build-demo-image.yml@master
    secrets: inherit
